/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Quick start tutorial (final), at
* https://www.jitblox.com/project/VymqwxT3SC/quick-start-tutorial-final
*/

import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { Destination } from '../../model';

@Component({
  selector: 'app-destinations',
  standalone: true,
  templateUrl: './destinations.component.html',
  styleUrls: ['./destinations.component.scss'],
  imports: [CommonModule]
})
export class DestinationsComponent {
  public destinationNames: string[] = ['Swiss Alps', 'Rome', 'Tokyo', 'Maldives', 'Tanzania', 'Great Barrier Reef', 'Petra', 'Glacier National Park', 'Paris', 'Costa Rica'];

  public destinations: Destination[] = [
    {
      name: 'Swiss Alps',
      photoUrl: 'https://media.jitblox.com/docs/quick-start/swiss-alps.png'
    },
    {
      name: 'Rome',
      photoUrl: 'https://media.jitblox.com/docs/quick-start/rome.png'
    },
    {
      name: 'Tokyo',
      photoUrl: 'https://media.jitblox.com/docs/quick-start/tokyo.png'
    },
    {
      name: 'Maldives',
      photoUrl: 'https://media.jitblox.com/docs/quick-start/maldives.png'
    },
    {
      name: 'Tanzania',
      photoUrl: 'https://media.jitblox.com/docs/quick-start/tanzania.png'
    },
    {
      name: 'Great Barrier Reef',
      photoUrl: 'https://media.jitblox.com/docs/quick-start/great-barrier-reef.png'
    },
    {
      name: 'Petra',
      photoUrl: 'https://media.jitblox.com/docs/quick-start/petra.jpg'
    },
    {
      name: 'Glacier National Park',
      photoUrl: 'https://media.jitblox.com/docs/quick-start/glacier-national-park.jpg'
    },
    {
      name: 'Paris',
      photoUrl: 'https://media.jitblox.com/docs/quick-start/paris.jpg'
    },
    {
      name: 'Costa Rica',
      photoUrl: 'https://media.jitblox.com/docs/quick-start/costa rica.jpg'
    }
  ];

  constructor() {}
}
